name: sql-installation
on: [push, pull_request]

jobs:
  Installation:

    runs-on: [self-hosted]    
    steps:
      - uses: actions/checkout@v2

      - name: Run the action
        uses: ./
        with:
          install: sqlengine, sqlclient, sqlpackage, localdb
          sa-password: c0MplicatedP@ssword
          show-log: true
          collation: Latin1_General_BIN

      - name: Run sqlcmd
        run: sqlcmd -S localhost -U sa -P c0MplicatedP@ssword -d tempdb -Q "SELECT @@version;"

      - name: Check collation
        shell: powershell
        run: |
          ./Test-Collation -ExpectedCollation Latin1_General_BIN -UserName sa -Password c0MplicatedP@ssword
